[workspace]
resolver = "2"
members = [ "aarm", "aarm_core","aarm_evm", "examples/compliance_circuit", "examples/trivial_logic", "examples/kudo_application" ]

[profile.bench]
lto = true

[profile.dev]
opt-level = 3

[profile.release]
lto = true