[package]
name = "kudo_tx"
version = "0.1.0"
edition = "2021"

[dependencies]
aarm_core = { path = "../../../aarm_core" }
kudo_core = { path = "../kudo_core" }
aarm = { path = "../../../aarm" }
serde = { version = "1.0.197", default-features = false }
risc0-zkvm = { version = "^2.0.2", default-features = false, features = ['std', "unstable", "client"] }
compliance_circuit = { path = "../../compliance_circuit/methods", package = 'methods' }
trivial_logic = { path = "../../trivial_logic/trivial_logic" }
kudo_logic = { path = "../kudo_logic" }
denomination_logic = { path = "../denomination_logic" }
receive_logic = { path = "../receive_logic" }
