[package]
name = "receive"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
aarm_core = { path = "../../../../aarm_core" }
serde = { version = "1.0.197", default-features = false }
