[package]
name = "compliance_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
aarm-core = { path = "../../core" }
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "1.1.2"}
bincode = "1.3.3"